language: ruby
cache: bundler
sudo: false

rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3.1
  - 2.2.5

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.0_paperclip_master.gemfile

script: "bundle exec rake clean spec"

